# .ruff.toml

line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "I", "B", "UP", "SIM"]
ignore = ["F541"]

[format]
docstring-code-format = true

[lint.per-file-ignores]
"data/make_cardio_train_pickle.py" = ["UP009"]